# Generated by Django 2.1.7 on 2019-03-25 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intellectmoney', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='intellectmoney',
            name='paymentId',
            field=models.CharField(editable=False, max_length=255, null=True),
        ),
    ]
